enable-magisk-update = true # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1
patches-source = "crimera/piko"
cli-source = "ReVanced/revanced-cli"

[Twitter]
apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter"
build-mode = "apk"
dpi = "120-640dpi"
patches-version = "dev"
cli-version = "latest"
version = "latest"
